### ISSUE TITLE
Sorting doesn't work

### ISSUE THREAD

**Issue by faktorweb** [derhansen/plain_faq#29]
Regardless of what I set, there is always only a sorting by question (alphabetically ascending). 
(Version 2.0.2 on TYPO3 10.4.12)

**Comment by derhansen** [comment]
@faktorweb This problem occurs, when the default TypoScript template is not included. The default TypoScript template has only one setting `orderFieldAllowed = uid,question,sorting`, which defines the fieldnames that can be used for sorting. So if the setting is empty, sorting will always fallback to the default sorting (by question ascending).

**Comment by derhansen** [comment]
@faktorweb This problem occurs, when the default TypoScript template is not included. The default TypoScript template has only one setting `orderFieldAllowed = uid,question,sorting`, which defines the fieldnames that can be used for sorting. So if the setting is empty, sorting will always fallback to the default sorting (by question ascending).
