### ISSUE TITLE
Can't change template

### ISSUE THREAD

**Issue by baggyownz** [derhansen/plain_faq#57]
Hello,
always is used the default template from extension. My changes in typoscript to set an alternative template (List.html) doesn't accept.
The typoscript code is included and the pathes are correct.
TYPO3 version 11.5.4
plain_faq version: 3.0.3
Any idea?
Thank you

**Comment by schugabe** [comment]
I have the same problem. The issue is that the key in the ts config does not match the name in ext_localconf any more.

If you add a ts setup for plugin.tx_plainfaq without the suffix _pi1 it uses the correct path
```
plugin.tx_plainfaq {
  view {
    templateRootPaths.1 = EXT:...
    partialRootPaths.1 = EXT:...
    layoutRootPaths.1 = EXT:..
  }
  settings {
    orderFieldAllowed = uid,question,sorting
  }
}```

**Comment by baggyownz** [comment]
Thank you for your help

**Comment by cyMarvin** [comment]
If you want to use less TypoScript, you can also just set the constants provided by the extension and add the following to the TypoScript **after** including the extensions' TypoScript setup.

`plugin.tx_plainfaq < plugin.tx_plainfaq_pi1`

Basically the answer from @schugabe , but with a little less code. ;)

**Comment by derhansen** [comment]
Thanks and sorry for the late answer. I somehow unsubscribed for notifications of my own git repository 🤷‍♂️

I changed the default TypoScript to `plugin.tx_plainfaq` and will add a hint to the release notes of the upcoming version, that local TypoScript with `_pi1` needs to be adapted.
