### ISSUE TITLE
[BUG] PageLayoutView - issue with getCategoryConjuction()

### ISSUE THREAD

**Issue by abvdveen** [derhansen/plain_faq#62]
There is an issue with getCategoryConjuction() in version 2.1.1 when plugin instances are migrated from irfaq. The value of 'settings.categoryConjunction' can be null, which causes a php error, as strtolower doesn't accept null values.

Code should be, for instance:
$categoryConjunction = null;
if (isset($this->getFieldFromFlexform('settings.categoryConjunction')) $categoryConjunction = strtolower($this->getFieldFromFlexform('settings.categoryConjunction'))

Or remove strtolower, as the only way settings.categoryConjunction can get a value, is through the flexform (not via TS), so it cannot be either lower or uppercase.

**Comment by derhansen** [comment]
Thanks for your report. I fixes this in development branch. 

Sidenote: Every plugin flexform setting following the `settings.` notation can also be set by TypoScript.

**Comment by abvdveen** [comment]
Thanks. Will you also fix it in the 2 branch? I'm still on Typo3 10 in this case, so need the version 2 of your extension.

Your sidenote doesn't apply to the settings in PageLayoutView, but I'm sure you are aware of that :)

**Comment by derhansen** [comment]
Now also fixed in 2.x branch

**Comment by abvdveen** [comment]
Thanks for the fast response! When will you release 2.1.2?
