### ISSUE TITLE
[TASK] Only use softref for images when rte_ckeditor_image is active

### ISSUE THREAD

**Issue by derhansen** [derhansen/plain_faq#68]

**Comment by hannesbochmann** [comment]
While you are at it. The softref "images" is in a normal TYPO3 installation invalid as well.

**Comment by hannesbochmann** [comment]
Thanks for the change. But as I mentioned before the "images" softref is invalid as well in a vanilla TYPO3 installation. @see https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/SoftReferences/Index.html#soft-references

**Comment by derhansen** [comment]
Yes, simple forgot that. How about a PR for the change?

**Comment by derhansen** [comment]
Thanks a lot. Will use the PR in version 3.x and 4.x
